export const SET_CAMERAS = "SET_CAMERAS";
export const PUSH_CAMERAS = "PUSH_CAMERAS";
export const SET_CAMERAS_LOADING = "SET_CAMERAS_LOADING";
export const SET_DETECTIONS = "SET_DETECTIONS";
export const PUSH_DETECTIONS = "PUSH_DETECTIONS";
export const SET_DETECTIONS_LOADING = "SET_DETECTIONS_LOADING";
